require 'bundler'
require 'colorize'
require 'date'
require 'epubinfo'
require 'sequel'
require 'sinatra/base'
require 'sinatra/json'
require 'yaml'

require_relative 'db/environment'
require_relative 'vendor/epubinfo/cover_patch'
require_relative 'lib/logging/logger'
