development:
  adapter: sqlite
  database: db/development.db
  max_connections: 5
  pool_timeout: 5000

production:
  adapter: sqlite
  database: db/production.db
  max_connections: 5
  pool_timeout: 5000

test: &test
  adapter: sqlite
  database: db/test.db
  max_connections: 5
  pool_timeout: 5000
